services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-container
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/db # Persistent data storage
      - ./mongodb/config:/data/configdb # Configuration data storage
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-secret}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-sample_db}
    networks:
      - local_docker

networks:
  local_docker:
    external: true
